// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DailyReward.proto

package com.genesis.protobuf;

public final class DailyRewardMessage {
  private DailyRewardMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CGGetDailyRewardOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.genesis.protobuf.CGGetDailyReward)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 rewardIndex = 1;</code>
     */
    boolean hasRewardIndex();
    /**
     * <code>required int32 rewardIndex = 1;</code>
     */
    int getRewardIndex();
  }
  /**
   * Protobuf type {@code com.genesis.protobuf.CGGetDailyReward}
   *
   * <pre>
   **
   * 领取日常奖励
   * </pre>
   */
  public static final class CGGetDailyReward extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.genesis.protobuf.CGGetDailyReward)
      CGGetDailyRewardOrBuilder {
    // Use CGGetDailyReward.newBuilder() to construct.
    private CGGetDailyReward(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CGGetDailyReward(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CGGetDailyReward defaultInstance;
    public static CGGetDailyReward getDefaultInstance() {
      return defaultInstance;
    }

    public CGGetDailyReward getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CGGetDailyReward(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              rewardIndex_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.genesis.protobuf.DailyRewardMessage.internal_static_com_genesis_protobuf_CGGetDailyReward_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.genesis.protobuf.DailyRewardMessage.internal_static_com_genesis_protobuf_CGGetDailyReward_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.genesis.protobuf.DailyRewardMessage.CGGetDailyReward.class, com.genesis.protobuf.DailyRewardMessage.CGGetDailyReward.Builder.class);
    }

    public static com.google.protobuf.Parser<CGGetDailyReward> PARSER =
        new com.google.protobuf.AbstractParser<CGGetDailyReward>() {
      public CGGetDailyReward parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CGGetDailyReward(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CGGetDailyReward> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int REWARDINDEX_FIELD_NUMBER = 1;
    private int rewardIndex_;
    /**
     * <code>required int32 rewardIndex = 1;</code>
     */
    public boolean hasRewardIndex() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 rewardIndex = 1;</code>
     */
    public int getRewardIndex() {
      return rewardIndex_;
    }

    private void initFields() {
      rewardIndex_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRewardIndex()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, rewardIndex_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, rewardIndex_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.genesis.protobuf.DailyRewardMessage.CGGetDailyReward parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.genesis.protobuf.DailyRewardMessage.CGGetDailyReward parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.genesis.protobuf.DailyRewardMessage.CGGetDailyReward parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.genesis.protobuf.DailyRewardMessage.CGGetDailyReward parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.genesis.protobuf.DailyRewardMessage.CGGetDailyReward parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.genesis.protobuf.DailyRewardMessage.CGGetDailyReward parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.genesis.protobuf.DailyRewardMessage.CGGetDailyReward parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.genesis.protobuf.DailyRewardMessage.CGGetDailyReward parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.genesis.protobuf.DailyRewardMessage.CGGetDailyReward parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.genesis.protobuf.DailyRewardMessage.CGGetDailyReward parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.genesis.protobuf.DailyRewardMessage.CGGetDailyReward prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.genesis.protobuf.CGGetDailyReward}
     *
     * <pre>
     **
     * 领取日常奖励
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.genesis.protobuf.CGGetDailyReward)
        com.genesis.protobuf.DailyRewardMessage.CGGetDailyRewardOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.genesis.protobuf.DailyRewardMessage.internal_static_com_genesis_protobuf_CGGetDailyReward_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.genesis.protobuf.DailyRewardMessage.internal_static_com_genesis_protobuf_CGGetDailyReward_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.genesis.protobuf.DailyRewardMessage.CGGetDailyReward.class, com.genesis.protobuf.DailyRewardMessage.CGGetDailyReward.Builder.class);
      }

      // Construct using com.genesis.protobuf.DailyRewardMessage.CGGetDailyReward.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        rewardIndex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.genesis.protobuf.DailyRewardMessage.internal_static_com_genesis_protobuf_CGGetDailyReward_descriptor;
      }

      public com.genesis.protobuf.DailyRewardMessage.CGGetDailyReward getDefaultInstanceForType() {
        return com.genesis.protobuf.DailyRewardMessage.CGGetDailyReward.getDefaultInstance();
      }

      public com.genesis.protobuf.DailyRewardMessage.CGGetDailyReward build() {
        com.genesis.protobuf.DailyRewardMessage.CGGetDailyReward result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.genesis.protobuf.DailyRewardMessage.CGGetDailyReward buildPartial() {
        com.genesis.protobuf.DailyRewardMessage.CGGetDailyReward result = new com.genesis.protobuf.DailyRewardMessage.CGGetDailyReward(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rewardIndex_ = rewardIndex_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.genesis.protobuf.DailyRewardMessage.CGGetDailyReward) {
          return mergeFrom((com.genesis.protobuf.DailyRewardMessage.CGGetDailyReward)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.genesis.protobuf.DailyRewardMessage.CGGetDailyReward other) {
        if (other == com.genesis.protobuf.DailyRewardMessage.CGGetDailyReward.getDefaultInstance()) return this;
        if (other.hasRewardIndex()) {
          setRewardIndex(other.getRewardIndex());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRewardIndex()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.genesis.protobuf.DailyRewardMessage.CGGetDailyReward parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.genesis.protobuf.DailyRewardMessage.CGGetDailyReward) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int rewardIndex_ ;
      /**
       * <code>required int32 rewardIndex = 1;</code>
       */
      public boolean hasRewardIndex() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 rewardIndex = 1;</code>
       */
      public int getRewardIndex() {
        return rewardIndex_;
      }
      /**
       * <code>required int32 rewardIndex = 1;</code>
       */
      public Builder setRewardIndex(int value) {
        bitField0_ |= 0x00000001;
        rewardIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 rewardIndex = 1;</code>
       */
      public Builder clearRewardIndex() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rewardIndex_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.genesis.protobuf.CGGetDailyReward)
    }

    static {
      defaultInstance = new CGGetDailyReward(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.genesis.protobuf.CGGetDailyReward)
  }

  public interface GCDailyRewardInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.genesis.protobuf.GCDailyRewardInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 timesOfReward = 1;</code>
     *
     * <pre>
     *当前将要领取的奖励的次数，从0开始
     * </pre>
     */
    boolean hasTimesOfReward();
    /**
     * <code>required int32 timesOfReward = 1;</code>
     *
     * <pre>
     *当前将要领取的奖励的次数，从0开始
     * </pre>
     */
    int getTimesOfReward();

    /**
     * <code>required int32 currentMonth = 2;</code>
     *
     * <pre>
     *当前月份
     * </pre>
     */
    boolean hasCurrentMonth();
    /**
     * <code>required int32 currentMonth = 2;</code>
     *
     * <pre>
     *当前月份
     * </pre>
     */
    int getCurrentMonth();

    /**
     * <code>required int32 indexOfHero = 3;</code>
     *
     * <pre>
     *英雄奖励在当前月份中的位置，从0开始
     * </pre>
     */
    boolean hasIndexOfHero();
    /**
     * <code>required int32 indexOfHero = 3;</code>
     *
     * <pre>
     *英雄奖励在当前月份中的位置，从0开始
     * </pre>
     */
    int getIndexOfHero();

    /**
     * <code>required bool hasNewReward = 4;</code>
     *
     * <pre>
     *是否可以领取奖励
     * </pre>
     */
    boolean hasHasNewReward();
    /**
     * <code>required bool hasNewReward = 4;</code>
     *
     * <pre>
     *是否可以领取奖励
     * </pre>
     */
    boolean getHasNewReward();
  }
  /**
   * Protobuf type {@code com.genesis.protobuf.GCDailyRewardInfo}
   *
   * <pre>
   **
   * 每日奖励的信息
   * </pre>
   */
  public static final class GCDailyRewardInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.genesis.protobuf.GCDailyRewardInfo)
      GCDailyRewardInfoOrBuilder {
    // Use GCDailyRewardInfo.newBuilder() to construct.
    private GCDailyRewardInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GCDailyRewardInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GCDailyRewardInfo defaultInstance;
    public static GCDailyRewardInfo getDefaultInstance() {
      return defaultInstance;
    }

    public GCDailyRewardInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GCDailyRewardInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              timesOfReward_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              currentMonth_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              indexOfHero_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              hasNewReward_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.genesis.protobuf.DailyRewardMessage.internal_static_com_genesis_protobuf_GCDailyRewardInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.genesis.protobuf.DailyRewardMessage.internal_static_com_genesis_protobuf_GCDailyRewardInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.genesis.protobuf.DailyRewardMessage.GCDailyRewardInfo.class, com.genesis.protobuf.DailyRewardMessage.GCDailyRewardInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<GCDailyRewardInfo> PARSER =
        new com.google.protobuf.AbstractParser<GCDailyRewardInfo>() {
      public GCDailyRewardInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GCDailyRewardInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GCDailyRewardInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TIMESOFREWARD_FIELD_NUMBER = 1;
    private int timesOfReward_;
    /**
     * <code>required int32 timesOfReward = 1;</code>
     *
     * <pre>
     *当前将要领取的奖励的次数，从0开始
     * </pre>
     */
    public boolean hasTimesOfReward() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 timesOfReward = 1;</code>
     *
     * <pre>
     *当前将要领取的奖励的次数，从0开始
     * </pre>
     */
    public int getTimesOfReward() {
      return timesOfReward_;
    }

    public static final int CURRENTMONTH_FIELD_NUMBER = 2;
    private int currentMonth_;
    /**
     * <code>required int32 currentMonth = 2;</code>
     *
     * <pre>
     *当前月份
     * </pre>
     */
    public boolean hasCurrentMonth() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 currentMonth = 2;</code>
     *
     * <pre>
     *当前月份
     * </pre>
     */
    public int getCurrentMonth() {
      return currentMonth_;
    }

    public static final int INDEXOFHERO_FIELD_NUMBER = 3;
    private int indexOfHero_;
    /**
     * <code>required int32 indexOfHero = 3;</code>
     *
     * <pre>
     *英雄奖励在当前月份中的位置，从0开始
     * </pre>
     */
    public boolean hasIndexOfHero() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 indexOfHero = 3;</code>
     *
     * <pre>
     *英雄奖励在当前月份中的位置，从0开始
     * </pre>
     */
    public int getIndexOfHero() {
      return indexOfHero_;
    }

    public static final int HASNEWREWARD_FIELD_NUMBER = 4;
    private boolean hasNewReward_;
    /**
     * <code>required bool hasNewReward = 4;</code>
     *
     * <pre>
     *是否可以领取奖励
     * </pre>
     */
    public boolean hasHasNewReward() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bool hasNewReward = 4;</code>
     *
     * <pre>
     *是否可以领取奖励
     * </pre>
     */
    public boolean getHasNewReward() {
      return hasNewReward_;
    }

    private void initFields() {
      timesOfReward_ = 0;
      currentMonth_ = 0;
      indexOfHero_ = 0;
      hasNewReward_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTimesOfReward()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCurrentMonth()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIndexOfHero()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHasNewReward()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, timesOfReward_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, currentMonth_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, indexOfHero_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, hasNewReward_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, timesOfReward_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, currentMonth_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, indexOfHero_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, hasNewReward_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.genesis.protobuf.DailyRewardMessage.GCDailyRewardInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.genesis.protobuf.DailyRewardMessage.GCDailyRewardInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.genesis.protobuf.DailyRewardMessage.GCDailyRewardInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.genesis.protobuf.DailyRewardMessage.GCDailyRewardInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.genesis.protobuf.DailyRewardMessage.GCDailyRewardInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.genesis.protobuf.DailyRewardMessage.GCDailyRewardInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.genesis.protobuf.DailyRewardMessage.GCDailyRewardInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.genesis.protobuf.DailyRewardMessage.GCDailyRewardInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.genesis.protobuf.DailyRewardMessage.GCDailyRewardInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.genesis.protobuf.DailyRewardMessage.GCDailyRewardInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.genesis.protobuf.DailyRewardMessage.GCDailyRewardInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.genesis.protobuf.GCDailyRewardInfo}
     *
     * <pre>
     **
     * 每日奖励的信息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.genesis.protobuf.GCDailyRewardInfo)
        com.genesis.protobuf.DailyRewardMessage.GCDailyRewardInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.genesis.protobuf.DailyRewardMessage.internal_static_com_genesis_protobuf_GCDailyRewardInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.genesis.protobuf.DailyRewardMessage.internal_static_com_genesis_protobuf_GCDailyRewardInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.genesis.protobuf.DailyRewardMessage.GCDailyRewardInfo.class, com.genesis.protobuf.DailyRewardMessage.GCDailyRewardInfo.Builder.class);
      }

      // Construct using com.genesis.protobuf.DailyRewardMessage.GCDailyRewardInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        timesOfReward_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        currentMonth_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        indexOfHero_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        hasNewReward_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.genesis.protobuf.DailyRewardMessage.internal_static_com_genesis_protobuf_GCDailyRewardInfo_descriptor;
      }

      public com.genesis.protobuf.DailyRewardMessage.GCDailyRewardInfo getDefaultInstanceForType() {
        return com.genesis.protobuf.DailyRewardMessage.GCDailyRewardInfo.getDefaultInstance();
      }

      public com.genesis.protobuf.DailyRewardMessage.GCDailyRewardInfo build() {
        com.genesis.protobuf.DailyRewardMessage.GCDailyRewardInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.genesis.protobuf.DailyRewardMessage.GCDailyRewardInfo buildPartial() {
        com.genesis.protobuf.DailyRewardMessage.GCDailyRewardInfo result = new com.genesis.protobuf.DailyRewardMessage.GCDailyRewardInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timesOfReward_ = timesOfReward_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.currentMonth_ = currentMonth_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.indexOfHero_ = indexOfHero_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.hasNewReward_ = hasNewReward_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.genesis.protobuf.DailyRewardMessage.GCDailyRewardInfo) {
          return mergeFrom((com.genesis.protobuf.DailyRewardMessage.GCDailyRewardInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.genesis.protobuf.DailyRewardMessage.GCDailyRewardInfo other) {
        if (other == com.genesis.protobuf.DailyRewardMessage.GCDailyRewardInfo.getDefaultInstance()) return this;
        if (other.hasTimesOfReward()) {
          setTimesOfReward(other.getTimesOfReward());
        }
        if (other.hasCurrentMonth()) {
          setCurrentMonth(other.getCurrentMonth());
        }
        if (other.hasIndexOfHero()) {
          setIndexOfHero(other.getIndexOfHero());
        }
        if (other.hasHasNewReward()) {
          setHasNewReward(other.getHasNewReward());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTimesOfReward()) {
          
          return false;
        }
        if (!hasCurrentMonth()) {
          
          return false;
        }
        if (!hasIndexOfHero()) {
          
          return false;
        }
        if (!hasHasNewReward()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.genesis.protobuf.DailyRewardMessage.GCDailyRewardInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.genesis.protobuf.DailyRewardMessage.GCDailyRewardInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int timesOfReward_ ;
      /**
       * <code>required int32 timesOfReward = 1;</code>
       *
       * <pre>
       *当前将要领取的奖励的次数，从0开始
       * </pre>
       */
      public boolean hasTimesOfReward() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 timesOfReward = 1;</code>
       *
       * <pre>
       *当前将要领取的奖励的次数，从0开始
       * </pre>
       */
      public int getTimesOfReward() {
        return timesOfReward_;
      }
      /**
       * <code>required int32 timesOfReward = 1;</code>
       *
       * <pre>
       *当前将要领取的奖励的次数，从0开始
       * </pre>
       */
      public Builder setTimesOfReward(int value) {
        bitField0_ |= 0x00000001;
        timesOfReward_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 timesOfReward = 1;</code>
       *
       * <pre>
       *当前将要领取的奖励的次数，从0开始
       * </pre>
       */
      public Builder clearTimesOfReward() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timesOfReward_ = 0;
        onChanged();
        return this;
      }

      private int currentMonth_ ;
      /**
       * <code>required int32 currentMonth = 2;</code>
       *
       * <pre>
       *当前月份
       * </pre>
       */
      public boolean hasCurrentMonth() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 currentMonth = 2;</code>
       *
       * <pre>
       *当前月份
       * </pre>
       */
      public int getCurrentMonth() {
        return currentMonth_;
      }
      /**
       * <code>required int32 currentMonth = 2;</code>
       *
       * <pre>
       *当前月份
       * </pre>
       */
      public Builder setCurrentMonth(int value) {
        bitField0_ |= 0x00000002;
        currentMonth_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 currentMonth = 2;</code>
       *
       * <pre>
       *当前月份
       * </pre>
       */
      public Builder clearCurrentMonth() {
        bitField0_ = (bitField0_ & ~0x00000002);
        currentMonth_ = 0;
        onChanged();
        return this;
      }

      private int indexOfHero_ ;
      /**
       * <code>required int32 indexOfHero = 3;</code>
       *
       * <pre>
       *英雄奖励在当前月份中的位置，从0开始
       * </pre>
       */
      public boolean hasIndexOfHero() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 indexOfHero = 3;</code>
       *
       * <pre>
       *英雄奖励在当前月份中的位置，从0开始
       * </pre>
       */
      public int getIndexOfHero() {
        return indexOfHero_;
      }
      /**
       * <code>required int32 indexOfHero = 3;</code>
       *
       * <pre>
       *英雄奖励在当前月份中的位置，从0开始
       * </pre>
       */
      public Builder setIndexOfHero(int value) {
        bitField0_ |= 0x00000004;
        indexOfHero_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 indexOfHero = 3;</code>
       *
       * <pre>
       *英雄奖励在当前月份中的位置，从0开始
       * </pre>
       */
      public Builder clearIndexOfHero() {
        bitField0_ = (bitField0_ & ~0x00000004);
        indexOfHero_ = 0;
        onChanged();
        return this;
      }

      private boolean hasNewReward_ ;
      /**
       * <code>required bool hasNewReward = 4;</code>
       *
       * <pre>
       *是否可以领取奖励
       * </pre>
       */
      public boolean hasHasNewReward() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bool hasNewReward = 4;</code>
       *
       * <pre>
       *是否可以领取奖励
       * </pre>
       */
      public boolean getHasNewReward() {
        return hasNewReward_;
      }
      /**
       * <code>required bool hasNewReward = 4;</code>
       *
       * <pre>
       *是否可以领取奖励
       * </pre>
       */
      public Builder setHasNewReward(boolean value) {
        bitField0_ |= 0x00000008;
        hasNewReward_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool hasNewReward = 4;</code>
       *
       * <pre>
       *是否可以领取奖励
       * </pre>
       */
      public Builder clearHasNewReward() {
        bitField0_ = (bitField0_ & ~0x00000008);
        hasNewReward_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.genesis.protobuf.GCDailyRewardInfo)
    }

    static {
      defaultInstance = new GCDailyRewardInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.genesis.protobuf.GCDailyRewardInfo)
  }

  public interface GCGetDailyRewardFailedOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.genesis.protobuf.GCGetDailyRewardFailed)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.genesis.protobuf.GCGetDailyRewardFailed}
   *
   * <pre>
   **
   * 每日奖励领取失败
   * </pre>
   */
  public static final class GCGetDailyRewardFailed extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.genesis.protobuf.GCGetDailyRewardFailed)
      GCGetDailyRewardFailedOrBuilder {
    // Use GCGetDailyRewardFailed.newBuilder() to construct.
    private GCGetDailyRewardFailed(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GCGetDailyRewardFailed(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GCGetDailyRewardFailed defaultInstance;
    public static GCGetDailyRewardFailed getDefaultInstance() {
      return defaultInstance;
    }

    public GCGetDailyRewardFailed getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GCGetDailyRewardFailed(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.genesis.protobuf.DailyRewardMessage.internal_static_com_genesis_protobuf_GCGetDailyRewardFailed_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.genesis.protobuf.DailyRewardMessage.internal_static_com_genesis_protobuf_GCGetDailyRewardFailed_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.genesis.protobuf.DailyRewardMessage.GCGetDailyRewardFailed.class, com.genesis.protobuf.DailyRewardMessage.GCGetDailyRewardFailed.Builder.class);
    }

    public static com.google.protobuf.Parser<GCGetDailyRewardFailed> PARSER =
        new com.google.protobuf.AbstractParser<GCGetDailyRewardFailed>() {
      public GCGetDailyRewardFailed parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GCGetDailyRewardFailed(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GCGetDailyRewardFailed> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.genesis.protobuf.DailyRewardMessage.GCGetDailyRewardFailed parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.genesis.protobuf.DailyRewardMessage.GCGetDailyRewardFailed parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.genesis.protobuf.DailyRewardMessage.GCGetDailyRewardFailed parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.genesis.protobuf.DailyRewardMessage.GCGetDailyRewardFailed parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.genesis.protobuf.DailyRewardMessage.GCGetDailyRewardFailed parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.genesis.protobuf.DailyRewardMessage.GCGetDailyRewardFailed parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.genesis.protobuf.DailyRewardMessage.GCGetDailyRewardFailed parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.genesis.protobuf.DailyRewardMessage.GCGetDailyRewardFailed parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.genesis.protobuf.DailyRewardMessage.GCGetDailyRewardFailed parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.genesis.protobuf.DailyRewardMessage.GCGetDailyRewardFailed parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.genesis.protobuf.DailyRewardMessage.GCGetDailyRewardFailed prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.genesis.protobuf.GCGetDailyRewardFailed}
     *
     * <pre>
     **
     * 每日奖励领取失败
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.genesis.protobuf.GCGetDailyRewardFailed)
        com.genesis.protobuf.DailyRewardMessage.GCGetDailyRewardFailedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.genesis.protobuf.DailyRewardMessage.internal_static_com_genesis_protobuf_GCGetDailyRewardFailed_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.genesis.protobuf.DailyRewardMessage.internal_static_com_genesis_protobuf_GCGetDailyRewardFailed_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.genesis.protobuf.DailyRewardMessage.GCGetDailyRewardFailed.class, com.genesis.protobuf.DailyRewardMessage.GCGetDailyRewardFailed.Builder.class);
      }

      // Construct using com.genesis.protobuf.DailyRewardMessage.GCGetDailyRewardFailed.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.genesis.protobuf.DailyRewardMessage.internal_static_com_genesis_protobuf_GCGetDailyRewardFailed_descriptor;
      }

      public com.genesis.protobuf.DailyRewardMessage.GCGetDailyRewardFailed getDefaultInstanceForType() {
        return com.genesis.protobuf.DailyRewardMessage.GCGetDailyRewardFailed.getDefaultInstance();
      }

      public com.genesis.protobuf.DailyRewardMessage.GCGetDailyRewardFailed build() {
        com.genesis.protobuf.DailyRewardMessage.GCGetDailyRewardFailed result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.genesis.protobuf.DailyRewardMessage.GCGetDailyRewardFailed buildPartial() {
        com.genesis.protobuf.DailyRewardMessage.GCGetDailyRewardFailed result = new com.genesis.protobuf.DailyRewardMessage.GCGetDailyRewardFailed(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.genesis.protobuf.DailyRewardMessage.GCGetDailyRewardFailed) {
          return mergeFrom((com.genesis.protobuf.DailyRewardMessage.GCGetDailyRewardFailed)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.genesis.protobuf.DailyRewardMessage.GCGetDailyRewardFailed other) {
        if (other == com.genesis.protobuf.DailyRewardMessage.GCGetDailyRewardFailed.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.genesis.protobuf.DailyRewardMessage.GCGetDailyRewardFailed parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.genesis.protobuf.DailyRewardMessage.GCGetDailyRewardFailed) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.genesis.protobuf.GCGetDailyRewardFailed)
    }

    static {
      defaultInstance = new GCGetDailyRewardFailed(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.genesis.protobuf.GCGetDailyRewardFailed)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_genesis_protobuf_CGGetDailyReward_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_genesis_protobuf_CGGetDailyReward_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_genesis_protobuf_GCDailyRewardInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_genesis_protobuf_GCDailyRewardInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_genesis_protobuf_GCGetDailyRewardFailed_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_genesis_protobuf_GCGetDailyRewardFailed_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021DailyReward.proto\022\024com.genesis.protobu" +
      "f\032\021MessageType.proto\".\n\020CGGetDailyReward" +
      "\022\023\n\013rewardIndex\030\001 \002(\005:\005\210\265\030\337\002\"r\n\021GCDailyR" +
      "ewardInfo\022\025\n\rtimesOfReward\030\001 \002(\005\022\024\n\014curr" +
      "entMonth\030\002 \002(\005\022\023\n\013indexOfHero\030\003 \002(\005\022\024\n\014h" +
      "asNewReward\030\004 \002(\010:\005\220\265\030\221\003\"\037\n\026GCGetDailyRe" +
      "wardFailed:\005\220\265\030\222\003B*\n\024com.genesis.protobu" +
      "fB\022DailyRewardMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.genesis.protobuf.MessageType.getDescriptor(),
        }, assigner);
    internal_static_com_genesis_protobuf_CGGetDailyReward_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_genesis_protobuf_CGGetDailyReward_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_genesis_protobuf_CGGetDailyReward_descriptor,
        new java.lang.String[] { "RewardIndex", });
    internal_static_com_genesis_protobuf_GCDailyRewardInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_genesis_protobuf_GCDailyRewardInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_genesis_protobuf_GCDailyRewardInfo_descriptor,
        new java.lang.String[] { "TimesOfReward", "CurrentMonth", "IndexOfHero", "HasNewReward", });
    internal_static_com_genesis_protobuf_GCGetDailyRewardFailed_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_genesis_protobuf_GCGetDailyRewardFailed_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_genesis_protobuf_GCGetDailyRewardFailed_descriptor,
        new java.lang.String[] { });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.genesis.protobuf.MessageType.cgMessageType);
    registry.add(com.genesis.protobuf.MessageType.gcMessageType);
    registry.add(com.genesis.protobuf.MessageType.gcMessageType);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.genesis.protobuf.MessageType.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
