// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Report.proto

package com.mokylin.bleach.protobuf;

public final class ReportMessage {
  private ReportMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ReportOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .com.mokylin.ReportInfo info = 1;
    /**
     * <code>required .com.mokylin.ReportInfo info = 1;</code>
     *
     * <pre>
     * 战斗初始双方信息
     * </pre>
     */
    boolean hasInfo();
    /**
     * <code>required .com.mokylin.ReportInfo info = 1;</code>
     *
     * <pre>
     * 战斗初始双方信息
     * </pre>
     */
    com.mokylin.bleach.protobuf.ReportMessage.ReportInfo getInfo();
    /**
     * <code>required .com.mokylin.ReportInfo info = 1;</code>
     *
     * <pre>
     * 战斗初始双方信息
     * </pre>
     */
    com.mokylin.bleach.protobuf.ReportMessage.ReportInfoOrBuilder getInfoOrBuilder();

    // required .com.mokylin.ReportRecord record = 2;
    /**
     * <code>required .com.mokylin.ReportRecord record = 2;</code>
     *
     * <pre>
     * 战斗流程记录
     * </pre>
     */
    boolean hasRecord();
    /**
     * <code>required .com.mokylin.ReportRecord record = 2;</code>
     *
     * <pre>
     * 战斗流程记录
     * </pre>
     */
    com.mokylin.bleach.protobuf.ReportMessage.ReportRecord getRecord();
    /**
     * <code>required .com.mokylin.ReportRecord record = 2;</code>
     *
     * <pre>
     * 战斗流程记录
     * </pre>
     */
    com.mokylin.bleach.protobuf.ReportMessage.ReportRecordOrBuilder getRecordOrBuilder();

    // required .com.mokylin.ReportResult result = 3;
    /**
     * <code>required .com.mokylin.ReportResult result = 3;</code>
     *
     * <pre>
     * 战斗结果
     * </pre>
     */
    boolean hasResult();
    /**
     * <code>required .com.mokylin.ReportResult result = 3;</code>
     *
     * <pre>
     * 战斗结果
     * </pre>
     */
    com.mokylin.bleach.protobuf.ReportMessage.ReportResult getResult();
    /**
     * <code>required .com.mokylin.ReportResult result = 3;</code>
     *
     * <pre>
     * 战斗结果
     * </pre>
     */
    com.mokylin.bleach.protobuf.ReportMessage.ReportResultOrBuilder getResultOrBuilder();
  }
  /**
   * Protobuf type {@code com.mokylin.Report}
   *
   * <pre>
   **
   * 战报
   * </pre>
   */
  public static final class Report extends
      com.google.protobuf.GeneratedMessage
      implements ReportOrBuilder {
    // Use Report.newBuilder() to construct.
    private Report(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Report(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Report defaultInstance;
    public static Report getDefaultInstance() {
      return defaultInstance;
    }

    public Report getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Report(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.mokylin.bleach.protobuf.ReportMessage.ReportInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = info_.toBuilder();
              }
              info_ = input.readMessage(com.mokylin.bleach.protobuf.ReportMessage.ReportInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(info_);
                info_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.mokylin.bleach.protobuf.ReportMessage.ReportRecord.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = record_.toBuilder();
              }
              record_ = input.readMessage(com.mokylin.bleach.protobuf.ReportMessage.ReportRecord.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(record_);
                record_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              com.mokylin.bleach.protobuf.ReportMessage.ReportResult.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = result_.toBuilder();
              }
              result_ = input.readMessage(com.mokylin.bleach.protobuf.ReportMessage.ReportResult.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(result_);
                result_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mokylin.bleach.protobuf.ReportMessage.internal_static_com_mokylin_Report_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mokylin.bleach.protobuf.ReportMessage.internal_static_com_mokylin_Report_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mokylin.bleach.protobuf.ReportMessage.Report.class, com.mokylin.bleach.protobuf.ReportMessage.Report.Builder.class);
    }

    public static com.google.protobuf.Parser<Report> PARSER =
        new com.google.protobuf.AbstractParser<Report>() {
      public Report parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Report(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Report> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .com.mokylin.ReportInfo info = 1;
    public static final int INFO_FIELD_NUMBER = 1;
    private com.mokylin.bleach.protobuf.ReportMessage.ReportInfo info_;
    /**
     * <code>required .com.mokylin.ReportInfo info = 1;</code>
     *
     * <pre>
     * 战斗初始双方信息
     * </pre>
     */
    public boolean hasInfo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.mokylin.ReportInfo info = 1;</code>
     *
     * <pre>
     * 战斗初始双方信息
     * </pre>
     */
    public com.mokylin.bleach.protobuf.ReportMessage.ReportInfo getInfo() {
      return info_;
    }
    /**
     * <code>required .com.mokylin.ReportInfo info = 1;</code>
     *
     * <pre>
     * 战斗初始双方信息
     * </pre>
     */
    public com.mokylin.bleach.protobuf.ReportMessage.ReportInfoOrBuilder getInfoOrBuilder() {
      return info_;
    }

    // required .com.mokylin.ReportRecord record = 2;
    public static final int RECORD_FIELD_NUMBER = 2;
    private com.mokylin.bleach.protobuf.ReportMessage.ReportRecord record_;
    /**
     * <code>required .com.mokylin.ReportRecord record = 2;</code>
     *
     * <pre>
     * 战斗流程记录
     * </pre>
     */
    public boolean hasRecord() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .com.mokylin.ReportRecord record = 2;</code>
     *
     * <pre>
     * 战斗流程记录
     * </pre>
     */
    public com.mokylin.bleach.protobuf.ReportMessage.ReportRecord getRecord() {
      return record_;
    }
    /**
     * <code>required .com.mokylin.ReportRecord record = 2;</code>
     *
     * <pre>
     * 战斗流程记录
     * </pre>
     */
    public com.mokylin.bleach.protobuf.ReportMessage.ReportRecordOrBuilder getRecordOrBuilder() {
      return record_;
    }

    // required .com.mokylin.ReportResult result = 3;
    public static final int RESULT_FIELD_NUMBER = 3;
    private com.mokylin.bleach.protobuf.ReportMessage.ReportResult result_;
    /**
     * <code>required .com.mokylin.ReportResult result = 3;</code>
     *
     * <pre>
     * 战斗结果
     * </pre>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .com.mokylin.ReportResult result = 3;</code>
     *
     * <pre>
     * 战斗结果
     * </pre>
     */
    public com.mokylin.bleach.protobuf.ReportMessage.ReportResult getResult() {
      return result_;
    }
    /**
     * <code>required .com.mokylin.ReportResult result = 3;</code>
     *
     * <pre>
     * 战斗结果
     * </pre>
     */
    public com.mokylin.bleach.protobuf.ReportMessage.ReportResultOrBuilder getResultOrBuilder() {
      return result_;
    }

    private void initFields() {
      info_ = com.mokylin.bleach.protobuf.ReportMessage.ReportInfo.getDefaultInstance();
      record_ = com.mokylin.bleach.protobuf.ReportMessage.ReportRecord.getDefaultInstance();
      result_ = com.mokylin.bleach.protobuf.ReportMessage.ReportResult.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasInfo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRecord()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, info_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, record_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, result_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, info_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, record_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, result_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mokylin.bleach.protobuf.ReportMessage.Report parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mokylin.bleach.protobuf.ReportMessage.Report parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mokylin.bleach.protobuf.ReportMessage.Report parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mokylin.bleach.protobuf.ReportMessage.Report parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mokylin.bleach.protobuf.ReportMessage.Report parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mokylin.bleach.protobuf.ReportMessage.Report parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mokylin.bleach.protobuf.ReportMessage.Report parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mokylin.bleach.protobuf.ReportMessage.Report parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mokylin.bleach.protobuf.ReportMessage.Report parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mokylin.bleach.protobuf.ReportMessage.Report parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mokylin.bleach.protobuf.ReportMessage.Report prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mokylin.Report}
     *
     * <pre>
     **
     * 战报
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mokylin.bleach.protobuf.ReportMessage.ReportOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mokylin.bleach.protobuf.ReportMessage.internal_static_com_mokylin_Report_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mokylin.bleach.protobuf.ReportMessage.internal_static_com_mokylin_Report_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mokylin.bleach.protobuf.ReportMessage.Report.class, com.mokylin.bleach.protobuf.ReportMessage.Report.Builder.class);
      }

      // Construct using com.mokylin.bleach.protobuf.ReportMessage.Report.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getInfoFieldBuilder();
          getRecordFieldBuilder();
          getResultFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (infoBuilder_ == null) {
          info_ = com.mokylin.bleach.protobuf.ReportMessage.ReportInfo.getDefaultInstance();
        } else {
          infoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (recordBuilder_ == null) {
          record_ = com.mokylin.bleach.protobuf.ReportMessage.ReportRecord.getDefaultInstance();
        } else {
          recordBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (resultBuilder_ == null) {
          result_ = com.mokylin.bleach.protobuf.ReportMessage.ReportResult.getDefaultInstance();
        } else {
          resultBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mokylin.bleach.protobuf.ReportMessage.internal_static_com_mokylin_Report_descriptor;
      }

      public com.mokylin.bleach.protobuf.ReportMessage.Report getDefaultInstanceForType() {
        return com.mokylin.bleach.protobuf.ReportMessage.Report.getDefaultInstance();
      }

      public com.mokylin.bleach.protobuf.ReportMessage.Report build() {
        com.mokylin.bleach.protobuf.ReportMessage.Report result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mokylin.bleach.protobuf.ReportMessage.Report buildPartial() {
        com.mokylin.bleach.protobuf.ReportMessage.Report result = new com.mokylin.bleach.protobuf.ReportMessage.Report(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (infoBuilder_ == null) {
          result.info_ = info_;
        } else {
          result.info_ = infoBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (recordBuilder_ == null) {
          result.record_ = record_;
        } else {
          result.record_ = recordBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (resultBuilder_ == null) {
          result.result_ = result_;
        } else {
          result.result_ = resultBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mokylin.bleach.protobuf.ReportMessage.Report) {
          return mergeFrom((com.mokylin.bleach.protobuf.ReportMessage.Report)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mokylin.bleach.protobuf.ReportMessage.Report other) {
        if (other == com.mokylin.bleach.protobuf.ReportMessage.Report.getDefaultInstance()) return this;
        if (other.hasInfo()) {
          mergeInfo(other.getInfo());
        }
        if (other.hasRecord()) {
          mergeRecord(other.getRecord());
        }
        if (other.hasResult()) {
          mergeResult(other.getResult());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasInfo()) {
          
          return false;
        }
        if (!hasRecord()) {
          
          return false;
        }
        if (!hasResult()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mokylin.bleach.protobuf.ReportMessage.Report parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mokylin.bleach.protobuf.ReportMessage.Report) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .com.mokylin.ReportInfo info = 1;
      private com.mokylin.bleach.protobuf.ReportMessage.ReportInfo info_ = com.mokylin.bleach.protobuf.ReportMessage.ReportInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.mokylin.bleach.protobuf.ReportMessage.ReportInfo, com.mokylin.bleach.protobuf.ReportMessage.ReportInfo.Builder, com.mokylin.bleach.protobuf.ReportMessage.ReportInfoOrBuilder> infoBuilder_;
      /**
       * <code>required .com.mokylin.ReportInfo info = 1;</code>
       *
       * <pre>
       * 战斗初始双方信息
       * </pre>
       */
      public boolean hasInfo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.mokylin.ReportInfo info = 1;</code>
       *
       * <pre>
       * 战斗初始双方信息
       * </pre>
       */
      public com.mokylin.bleach.protobuf.ReportMessage.ReportInfo getInfo() {
        if (infoBuilder_ == null) {
          return info_;
        } else {
          return infoBuilder_.getMessage();
        }
      }
      /**
       * <code>required .com.mokylin.ReportInfo info = 1;</code>
       *
       * <pre>
       * 战斗初始双方信息
       * </pre>
       */
      public Builder setInfo(com.mokylin.bleach.protobuf.ReportMessage.ReportInfo value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          info_ = value;
          onChanged();
        } else {
          infoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.mokylin.ReportInfo info = 1;</code>
       *
       * <pre>
       * 战斗初始双方信息
       * </pre>
       */
      public Builder setInfo(
          com.mokylin.bleach.protobuf.ReportMessage.ReportInfo.Builder builderForValue) {
        if (infoBuilder_ == null) {
          info_ = builderForValue.build();
          onChanged();
        } else {
          infoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.mokylin.ReportInfo info = 1;</code>
       *
       * <pre>
       * 战斗初始双方信息
       * </pre>
       */
      public Builder mergeInfo(com.mokylin.bleach.protobuf.ReportMessage.ReportInfo value) {
        if (infoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              info_ != com.mokylin.bleach.protobuf.ReportMessage.ReportInfo.getDefaultInstance()) {
            info_ =
              com.mokylin.bleach.protobuf.ReportMessage.ReportInfo.newBuilder(info_).mergeFrom(value).buildPartial();
          } else {
            info_ = value;
          }
          onChanged();
        } else {
          infoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.mokylin.ReportInfo info = 1;</code>
       *
       * <pre>
       * 战斗初始双方信息
       * </pre>
       */
      public Builder clearInfo() {
        if (infoBuilder_ == null) {
          info_ = com.mokylin.bleach.protobuf.ReportMessage.ReportInfo.getDefaultInstance();
          onChanged();
        } else {
          infoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .com.mokylin.ReportInfo info = 1;</code>
       *
       * <pre>
       * 战斗初始双方信息
       * </pre>
       */
      public com.mokylin.bleach.protobuf.ReportMessage.ReportInfo.Builder getInfoBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>required .com.mokylin.ReportInfo info = 1;</code>
       *
       * <pre>
       * 战斗初始双方信息
       * </pre>
       */
      public com.mokylin.bleach.protobuf.ReportMessage.ReportInfoOrBuilder getInfoOrBuilder() {
        if (infoBuilder_ != null) {
          return infoBuilder_.getMessageOrBuilder();
        } else {
          return info_;
        }
      }
      /**
       * <code>required .com.mokylin.ReportInfo info = 1;</code>
       *
       * <pre>
       * 战斗初始双方信息
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.mokylin.bleach.protobuf.ReportMessage.ReportInfo, com.mokylin.bleach.protobuf.ReportMessage.ReportInfo.Builder, com.mokylin.bleach.protobuf.ReportMessage.ReportInfoOrBuilder> 
          getInfoFieldBuilder() {
        if (infoBuilder_ == null) {
          infoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.mokylin.bleach.protobuf.ReportMessage.ReportInfo, com.mokylin.bleach.protobuf.ReportMessage.ReportInfo.Builder, com.mokylin.bleach.protobuf.ReportMessage.ReportInfoOrBuilder>(
                  info_,
                  getParentForChildren(),
                  isClean());
          info_ = null;
        }
        return infoBuilder_;
      }

      // required .com.mokylin.ReportRecord record = 2;
      private com.mokylin.bleach.protobuf.ReportMessage.ReportRecord record_ = com.mokylin.bleach.protobuf.ReportMessage.ReportRecord.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.mokylin.bleach.protobuf.ReportMessage.ReportRecord, com.mokylin.bleach.protobuf.ReportMessage.ReportRecord.Builder, com.mokylin.bleach.protobuf.ReportMessage.ReportRecordOrBuilder> recordBuilder_;
      /**
       * <code>required .com.mokylin.ReportRecord record = 2;</code>
       *
       * <pre>
       * 战斗流程记录
       * </pre>
       */
      public boolean hasRecord() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .com.mokylin.ReportRecord record = 2;</code>
       *
       * <pre>
       * 战斗流程记录
       * </pre>
       */
      public com.mokylin.bleach.protobuf.ReportMessage.ReportRecord getRecord() {
        if (recordBuilder_ == null) {
          return record_;
        } else {
          return recordBuilder_.getMessage();
        }
      }
      /**
       * <code>required .com.mokylin.ReportRecord record = 2;</code>
       *
       * <pre>
       * 战斗流程记录
       * </pre>
       */
      public Builder setRecord(com.mokylin.bleach.protobuf.ReportMessage.ReportRecord value) {
        if (recordBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          record_ = value;
          onChanged();
        } else {
          recordBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .com.mokylin.ReportRecord record = 2;</code>
       *
       * <pre>
       * 战斗流程记录
       * </pre>
       */
      public Builder setRecord(
          com.mokylin.bleach.protobuf.ReportMessage.ReportRecord.Builder builderForValue) {
        if (recordBuilder_ == null) {
          record_ = builderForValue.build();
          onChanged();
        } else {
          recordBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .com.mokylin.ReportRecord record = 2;</code>
       *
       * <pre>
       * 战斗流程记录
       * </pre>
       */
      public Builder mergeRecord(com.mokylin.bleach.protobuf.ReportMessage.ReportRecord value) {
        if (recordBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              record_ != com.mokylin.bleach.protobuf.ReportMessage.ReportRecord.getDefaultInstance()) {
            record_ =
              com.mokylin.bleach.protobuf.ReportMessage.ReportRecord.newBuilder(record_).mergeFrom(value).buildPartial();
          } else {
            record_ = value;
          }
          onChanged();
        } else {
          recordBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .com.mokylin.ReportRecord record = 2;</code>
       *
       * <pre>
       * 战斗流程记录
       * </pre>
       */
      public Builder clearRecord() {
        if (recordBuilder_ == null) {
          record_ = com.mokylin.bleach.protobuf.ReportMessage.ReportRecord.getDefaultInstance();
          onChanged();
        } else {
          recordBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .com.mokylin.ReportRecord record = 2;</code>
       *
       * <pre>
       * 战斗流程记录
       * </pre>
       */
      public com.mokylin.bleach.protobuf.ReportMessage.ReportRecord.Builder getRecordBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getRecordFieldBuilder().getBuilder();
      }
      /**
       * <code>required .com.mokylin.ReportRecord record = 2;</code>
       *
       * <pre>
       * 战斗流程记录
       * </pre>
       */
      public com.mokylin.bleach.protobuf.ReportMessage.ReportRecordOrBuilder getRecordOrBuilder() {
        if (recordBuilder_ != null) {
          return recordBuilder_.getMessageOrBuilder();
        } else {
          return record_;
        }
      }
      /**
       * <code>required .com.mokylin.ReportRecord record = 2;</code>
       *
       * <pre>
       * 战斗流程记录
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.mokylin.bleach.protobuf.ReportMessage.ReportRecord, com.mokylin.bleach.protobuf.ReportMessage.ReportRecord.Builder, com.mokylin.bleach.protobuf.ReportMessage.ReportRecordOrBuilder> 
          getRecordFieldBuilder() {
        if (recordBuilder_ == null) {
          recordBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.mokylin.bleach.protobuf.ReportMessage.ReportRecord, com.mokylin.bleach.protobuf.ReportMessage.ReportRecord.Builder, com.mokylin.bleach.protobuf.ReportMessage.ReportRecordOrBuilder>(
                  record_,
                  getParentForChildren(),
                  isClean());
          record_ = null;
        }
        return recordBuilder_;
      }

      // required .com.mokylin.ReportResult result = 3;
      private com.mokylin.bleach.protobuf.ReportMessage.ReportResult result_ = com.mokylin.bleach.protobuf.ReportMessage.ReportResult.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.mokylin.bleach.protobuf.ReportMessage.ReportResult, com.mokylin.bleach.protobuf.ReportMessage.ReportResult.Builder, com.mokylin.bleach.protobuf.ReportMessage.ReportResultOrBuilder> resultBuilder_;
      /**
       * <code>required .com.mokylin.ReportResult result = 3;</code>
       *
       * <pre>
       * 战斗结果
       * </pre>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .com.mokylin.ReportResult result = 3;</code>
       *
       * <pre>
       * 战斗结果
       * </pre>
       */
      public com.mokylin.bleach.protobuf.ReportMessage.ReportResult getResult() {
        if (resultBuilder_ == null) {
          return result_;
        } else {
          return resultBuilder_.getMessage();
        }
      }
      /**
       * <code>required .com.mokylin.ReportResult result = 3;</code>
       *
       * <pre>
       * 战斗结果
       * </pre>
       */
      public Builder setResult(com.mokylin.bleach.protobuf.ReportMessage.ReportResult value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          result_ = value;
          onChanged();
        } else {
          resultBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .com.mokylin.ReportResult result = 3;</code>
       *
       * <pre>
       * 战斗结果
       * </pre>
       */
      public Builder setResult(
          com.mokylin.bleach.protobuf.ReportMessage.ReportResult.Builder builderForValue) {
        if (resultBuilder_ == null) {
          result_ = builderForValue.build();
          onChanged();
        } else {
          resultBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .com.mokylin.ReportResult result = 3;</code>
       *
       * <pre>
       * 战斗结果
       * </pre>
       */
      public Builder mergeResult(com.mokylin.bleach.protobuf.ReportMessage.ReportResult value) {
        if (resultBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              result_ != com.mokylin.bleach.protobuf.ReportMessage.ReportResult.getDefaultInstance()) {
            result_ =
              com.mokylin.bleach.protobuf.ReportMessage.ReportResult.newBuilder(result_).mergeFrom(value).buildPartial();
          } else {
            result_ = value;
          }
          onChanged();
        } else {
          resultBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .com.mokylin.ReportResult result = 3;</code>
       *
       * <pre>
       * 战斗结果
       * </pre>
       */
      public Builder clearResult() {
        if (resultBuilder_ == null) {
          result_ = com.mokylin.bleach.protobuf.ReportMessage.ReportResult.getDefaultInstance();
          onChanged();
        } else {
          resultBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>required .com.mokylin.ReportResult result = 3;</code>
       *
       * <pre>
       * 战斗结果
       * </pre>
       */
      public com.mokylin.bleach.protobuf.ReportMessage.ReportResult.Builder getResultBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getResultFieldBuilder().getBuilder();
      }
      /**
       * <code>required .com.mokylin.ReportResult result = 3;</code>
       *
       * <pre>
       * 战斗结果
       * </pre>
       */
      public com.mokylin.bleach.protobuf.ReportMessage.ReportResultOrBuilder getResultOrBuilder() {
        if (resultBuilder_ != null) {
          return resultBuilder_.getMessageOrBuilder();
        } else {
          return result_;
        }
      }
      /**
       * <code>required .com.mokylin.ReportResult result = 3;</code>
       *
       * <pre>
       * 战斗结果
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.mokylin.bleach.protobuf.ReportMessage.ReportResult, com.mokylin.bleach.protobuf.ReportMessage.ReportResult.Builder, com.mokylin.bleach.protobuf.ReportMessage.ReportResultOrBuilder> 
          getResultFieldBuilder() {
        if (resultBuilder_ == null) {
          resultBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.mokylin.bleach.protobuf.ReportMessage.ReportResult, com.mokylin.bleach.protobuf.ReportMessage.ReportResult.Builder, com.mokylin.bleach.protobuf.ReportMessage.ReportResultOrBuilder>(
                  result_,
                  getParentForChildren(),
                  isClean());
          result_ = null;
        }
        return resultBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.mokylin.Report)
    }

    static {
      defaultInstance = new Report(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.mokylin.Report)
  }

  public interface ReportInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.mokylin.ReportInfo}
   *
   * <pre>
   **初始信息 
   * </pre>
   */
  public static final class ReportInfo extends
      com.google.protobuf.GeneratedMessage
      implements ReportInfoOrBuilder {
    // Use ReportInfo.newBuilder() to construct.
    private ReportInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReportInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReportInfo defaultInstance;
    public static ReportInfo getDefaultInstance() {
      return defaultInstance;
    }

    public ReportInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReportInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mokylin.bleach.protobuf.ReportMessage.internal_static_com_mokylin_ReportInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mokylin.bleach.protobuf.ReportMessage.internal_static_com_mokylin_ReportInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mokylin.bleach.protobuf.ReportMessage.ReportInfo.class, com.mokylin.bleach.protobuf.ReportMessage.ReportInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<ReportInfo> PARSER =
        new com.google.protobuf.AbstractParser<ReportInfo>() {
      public ReportInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReportInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReportInfo> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mokylin.bleach.protobuf.ReportMessage.ReportInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mokylin.bleach.protobuf.ReportMessage.ReportInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mokylin.bleach.protobuf.ReportMessage.ReportInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mokylin.bleach.protobuf.ReportMessage.ReportInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mokylin.bleach.protobuf.ReportMessage.ReportInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mokylin.bleach.protobuf.ReportMessage.ReportInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mokylin.bleach.protobuf.ReportMessage.ReportInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mokylin.bleach.protobuf.ReportMessage.ReportInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mokylin.bleach.protobuf.ReportMessage.ReportInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mokylin.bleach.protobuf.ReportMessage.ReportInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mokylin.bleach.protobuf.ReportMessage.ReportInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mokylin.ReportInfo}
     *
     * <pre>
     **初始信息 
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mokylin.bleach.protobuf.ReportMessage.ReportInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mokylin.bleach.protobuf.ReportMessage.internal_static_com_mokylin_ReportInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mokylin.bleach.protobuf.ReportMessage.internal_static_com_mokylin_ReportInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mokylin.bleach.protobuf.ReportMessage.ReportInfo.class, com.mokylin.bleach.protobuf.ReportMessage.ReportInfo.Builder.class);
      }

      // Construct using com.mokylin.bleach.protobuf.ReportMessage.ReportInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mokylin.bleach.protobuf.ReportMessage.internal_static_com_mokylin_ReportInfo_descriptor;
      }

      public com.mokylin.bleach.protobuf.ReportMessage.ReportInfo getDefaultInstanceForType() {
        return com.mokylin.bleach.protobuf.ReportMessage.ReportInfo.getDefaultInstance();
      }

      public com.mokylin.bleach.protobuf.ReportMessage.ReportInfo build() {
        com.mokylin.bleach.protobuf.ReportMessage.ReportInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mokylin.bleach.protobuf.ReportMessage.ReportInfo buildPartial() {
        com.mokylin.bleach.protobuf.ReportMessage.ReportInfo result = new com.mokylin.bleach.protobuf.ReportMessage.ReportInfo(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mokylin.bleach.protobuf.ReportMessage.ReportInfo) {
          return mergeFrom((com.mokylin.bleach.protobuf.ReportMessage.ReportInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mokylin.bleach.protobuf.ReportMessage.ReportInfo other) {
        if (other == com.mokylin.bleach.protobuf.ReportMessage.ReportInfo.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mokylin.bleach.protobuf.ReportMessage.ReportInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mokylin.bleach.protobuf.ReportMessage.ReportInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.mokylin.ReportInfo)
    }

    static {
      defaultInstance = new ReportInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.mokylin.ReportInfo)
  }

  public interface ReportRecordOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.mokylin.ReportRecord}
   *
   * <pre>
   **战斗记录 
   * </pre>
   */
  public static final class ReportRecord extends
      com.google.protobuf.GeneratedMessage
      implements ReportRecordOrBuilder {
    // Use ReportRecord.newBuilder() to construct.
    private ReportRecord(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReportRecord(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReportRecord defaultInstance;
    public static ReportRecord getDefaultInstance() {
      return defaultInstance;
    }

    public ReportRecord getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReportRecord(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mokylin.bleach.protobuf.ReportMessage.internal_static_com_mokylin_ReportRecord_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mokylin.bleach.protobuf.ReportMessage.internal_static_com_mokylin_ReportRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mokylin.bleach.protobuf.ReportMessage.ReportRecord.class, com.mokylin.bleach.protobuf.ReportMessage.ReportRecord.Builder.class);
    }

    public static com.google.protobuf.Parser<ReportRecord> PARSER =
        new com.google.protobuf.AbstractParser<ReportRecord>() {
      public ReportRecord parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReportRecord(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReportRecord> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mokylin.bleach.protobuf.ReportMessage.ReportRecord parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mokylin.bleach.protobuf.ReportMessage.ReportRecord parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mokylin.bleach.protobuf.ReportMessage.ReportRecord parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mokylin.bleach.protobuf.ReportMessage.ReportRecord parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mokylin.bleach.protobuf.ReportMessage.ReportRecord parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mokylin.bleach.protobuf.ReportMessage.ReportRecord parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mokylin.bleach.protobuf.ReportMessage.ReportRecord parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mokylin.bleach.protobuf.ReportMessage.ReportRecord parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mokylin.bleach.protobuf.ReportMessage.ReportRecord parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mokylin.bleach.protobuf.ReportMessage.ReportRecord parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mokylin.bleach.protobuf.ReportMessage.ReportRecord prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mokylin.ReportRecord}
     *
     * <pre>
     **战斗记录 
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mokylin.bleach.protobuf.ReportMessage.ReportRecordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mokylin.bleach.protobuf.ReportMessage.internal_static_com_mokylin_ReportRecord_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mokylin.bleach.protobuf.ReportMessage.internal_static_com_mokylin_ReportRecord_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mokylin.bleach.protobuf.ReportMessage.ReportRecord.class, com.mokylin.bleach.protobuf.ReportMessage.ReportRecord.Builder.class);
      }

      // Construct using com.mokylin.bleach.protobuf.ReportMessage.ReportRecord.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mokylin.bleach.protobuf.ReportMessage.internal_static_com_mokylin_ReportRecord_descriptor;
      }

      public com.mokylin.bleach.protobuf.ReportMessage.ReportRecord getDefaultInstanceForType() {
        return com.mokylin.bleach.protobuf.ReportMessage.ReportRecord.getDefaultInstance();
      }

      public com.mokylin.bleach.protobuf.ReportMessage.ReportRecord build() {
        com.mokylin.bleach.protobuf.ReportMessage.ReportRecord result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mokylin.bleach.protobuf.ReportMessage.ReportRecord buildPartial() {
        com.mokylin.bleach.protobuf.ReportMessage.ReportRecord result = new com.mokylin.bleach.protobuf.ReportMessage.ReportRecord(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mokylin.bleach.protobuf.ReportMessage.ReportRecord) {
          return mergeFrom((com.mokylin.bleach.protobuf.ReportMessage.ReportRecord)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mokylin.bleach.protobuf.ReportMessage.ReportRecord other) {
        if (other == com.mokylin.bleach.protobuf.ReportMessage.ReportRecord.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mokylin.bleach.protobuf.ReportMessage.ReportRecord parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mokylin.bleach.protobuf.ReportMessage.ReportRecord) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.mokylin.ReportRecord)
    }

    static {
      defaultInstance = new ReportRecord(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.mokylin.ReportRecord)
  }

  public interface ReportResultOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.mokylin.ReportResult}
   *
   * <pre>
   **战斗结果 
   * </pre>
   */
  public static final class ReportResult extends
      com.google.protobuf.GeneratedMessage
      implements ReportResultOrBuilder {
    // Use ReportResult.newBuilder() to construct.
    private ReportResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReportResult(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReportResult defaultInstance;
    public static ReportResult getDefaultInstance() {
      return defaultInstance;
    }

    public ReportResult getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReportResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mokylin.bleach.protobuf.ReportMessage.internal_static_com_mokylin_ReportResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mokylin.bleach.protobuf.ReportMessage.internal_static_com_mokylin_ReportResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mokylin.bleach.protobuf.ReportMessage.ReportResult.class, com.mokylin.bleach.protobuf.ReportMessage.ReportResult.Builder.class);
    }

    public static com.google.protobuf.Parser<ReportResult> PARSER =
        new com.google.protobuf.AbstractParser<ReportResult>() {
      public ReportResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReportResult(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReportResult> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mokylin.bleach.protobuf.ReportMessage.ReportResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mokylin.bleach.protobuf.ReportMessage.ReportResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mokylin.bleach.protobuf.ReportMessage.ReportResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mokylin.bleach.protobuf.ReportMessage.ReportResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mokylin.bleach.protobuf.ReportMessage.ReportResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mokylin.bleach.protobuf.ReportMessage.ReportResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mokylin.bleach.protobuf.ReportMessage.ReportResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mokylin.bleach.protobuf.ReportMessage.ReportResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mokylin.bleach.protobuf.ReportMessage.ReportResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mokylin.bleach.protobuf.ReportMessage.ReportResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mokylin.bleach.protobuf.ReportMessage.ReportResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mokylin.ReportResult}
     *
     * <pre>
     **战斗结果 
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mokylin.bleach.protobuf.ReportMessage.ReportResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mokylin.bleach.protobuf.ReportMessage.internal_static_com_mokylin_ReportResult_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mokylin.bleach.protobuf.ReportMessage.internal_static_com_mokylin_ReportResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mokylin.bleach.protobuf.ReportMessage.ReportResult.class, com.mokylin.bleach.protobuf.ReportMessage.ReportResult.Builder.class);
      }

      // Construct using com.mokylin.bleach.protobuf.ReportMessage.ReportResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mokylin.bleach.protobuf.ReportMessage.internal_static_com_mokylin_ReportResult_descriptor;
      }

      public com.mokylin.bleach.protobuf.ReportMessage.ReportResult getDefaultInstanceForType() {
        return com.mokylin.bleach.protobuf.ReportMessage.ReportResult.getDefaultInstance();
      }

      public com.mokylin.bleach.protobuf.ReportMessage.ReportResult build() {
        com.mokylin.bleach.protobuf.ReportMessage.ReportResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mokylin.bleach.protobuf.ReportMessage.ReportResult buildPartial() {
        com.mokylin.bleach.protobuf.ReportMessage.ReportResult result = new com.mokylin.bleach.protobuf.ReportMessage.ReportResult(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mokylin.bleach.protobuf.ReportMessage.ReportResult) {
          return mergeFrom((com.mokylin.bleach.protobuf.ReportMessage.ReportResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mokylin.bleach.protobuf.ReportMessage.ReportResult other) {
        if (other == com.mokylin.bleach.protobuf.ReportMessage.ReportResult.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mokylin.bleach.protobuf.ReportMessage.ReportResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mokylin.bleach.protobuf.ReportMessage.ReportResult) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.mokylin.ReportResult)
    }

    static {
      defaultInstance = new ReportResult(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.mokylin.ReportResult)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mokylin_Report_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mokylin_Report_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mokylin_ReportInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mokylin_ReportInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mokylin_ReportRecord_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mokylin_ReportRecord_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mokylin_ReportResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mokylin_ReportResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Report.proto\022\013com.mokylin\032\021MessageType" +
      ".proto\"\205\001\n\006Report\022%\n\004info\030\001 \002(\0132\027.com.mo" +
      "kylin.ReportInfo\022)\n\006record\030\002 \002(\0132\031.com.m" +
      "okylin.ReportRecord\022)\n\006result\030\003 \002(\0132\031.co" +
      "m.mokylin.ReportResult\"\014\n\nReportInfo\"\016\n\014" +
      "ReportRecord\"\016\n\014ReportResultB,\n\033com.moky" +
      "lin.bleach.protobufB\rReportMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_mokylin_Report_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_mokylin_Report_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_mokylin_Report_descriptor,
              new java.lang.String[] { "Info", "Record", "Result", });
          internal_static_com_mokylin_ReportInfo_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_mokylin_ReportInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_mokylin_ReportInfo_descriptor,
              new java.lang.String[] { });
          internal_static_com_mokylin_ReportRecord_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_mokylin_ReportRecord_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_mokylin_ReportRecord_descriptor,
              new java.lang.String[] { });
          internal_static_com_mokylin_ReportResult_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_mokylin_ReportResult_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_mokylin_ReportResult_descriptor,
              new java.lang.String[] { });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.mokylin.bleach.protobuf.MessageType.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
