// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db/DBOnlineMsg.proto

package com.icewind.protobuf.db;

public final class DBOnlineMsgBlob {
  private DBOnlineMsgBlob() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface OnlineMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.icewind.protobuf.OnlineMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.icewind.protobuf.MsgData msgDatas = 1;</code>
     */
    java.util.List<com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData> 
        getMsgDatasList();
    /**
     * <code>repeated .com.icewind.protobuf.MsgData msgDatas = 1;</code>
     */
    com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData getMsgDatas(int index);
    /**
     * <code>repeated .com.icewind.protobuf.MsgData msgDatas = 1;</code>
     */
    int getMsgDatasCount();
    /**
     * <code>repeated .com.icewind.protobuf.MsgData msgDatas = 1;</code>
     */
    java.util.List<? extends com.icewind.protobuf.db.DBOnlineMsgBlob.MsgDataOrBuilder> 
        getMsgDatasOrBuilderList();
    /**
     * <code>repeated .com.icewind.protobuf.MsgData msgDatas = 1;</code>
     */
    com.icewind.protobuf.db.DBOnlineMsgBlob.MsgDataOrBuilder getMsgDatasOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.icewind.protobuf.OnlineMsg}
   *
   * <pre>
   **
   * 玩家未处理的在线消息
   * </pre>
   */
  public static final class OnlineMsg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.icewind.protobuf.OnlineMsg)
      OnlineMsgOrBuilder {
    // Use OnlineMsg.newBuilder() to construct.
    private OnlineMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OnlineMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OnlineMsg defaultInstance;
    public static OnlineMsg getDefaultInstance() {
      return defaultInstance;
    }

    public OnlineMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private OnlineMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                msgDatas_ = new java.util.ArrayList<com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData>();
                mutable_bitField0_ |= 0x00000001;
              }
              msgDatas_.add(input.readMessage(com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          msgDatas_ = java.util.Collections.unmodifiableList(msgDatas_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.icewind.protobuf.db.DBOnlineMsgBlob.internal_static_com_icewind_protobuf_OnlineMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.icewind.protobuf.db.DBOnlineMsgBlob.internal_static_com_icewind_protobuf_OnlineMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.icewind.protobuf.db.DBOnlineMsgBlob.OnlineMsg.class, com.icewind.protobuf.db.DBOnlineMsgBlob.OnlineMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<OnlineMsg> PARSER =
        new com.google.protobuf.AbstractParser<OnlineMsg>() {
      public OnlineMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OnlineMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<OnlineMsg> getParserForType() {
      return PARSER;
    }

    public static final int MSGDATAS_FIELD_NUMBER = 1;
    private java.util.List<com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData> msgDatas_;
    /**
     * <code>repeated .com.icewind.protobuf.MsgData msgDatas = 1;</code>
     */
    public java.util.List<com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData> getMsgDatasList() {
      return msgDatas_;
    }
    /**
     * <code>repeated .com.icewind.protobuf.MsgData msgDatas = 1;</code>
     */
    public java.util.List<? extends com.icewind.protobuf.db.DBOnlineMsgBlob.MsgDataOrBuilder> 
        getMsgDatasOrBuilderList() {
      return msgDatas_;
    }
    /**
     * <code>repeated .com.icewind.protobuf.MsgData msgDatas = 1;</code>
     */
    public int getMsgDatasCount() {
      return msgDatas_.size();
    }
    /**
     * <code>repeated .com.icewind.protobuf.MsgData msgDatas = 1;</code>
     */
    public com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData getMsgDatas(int index) {
      return msgDatas_.get(index);
    }
    /**
     * <code>repeated .com.icewind.protobuf.MsgData msgDatas = 1;</code>
     */
    public com.icewind.protobuf.db.DBOnlineMsgBlob.MsgDataOrBuilder getMsgDatasOrBuilder(
        int index) {
      return msgDatas_.get(index);
    }

    private void initFields() {
      msgDatas_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getMsgDatasCount(); i++) {
        if (!getMsgDatas(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < msgDatas_.size(); i++) {
        output.writeMessage(1, msgDatas_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < msgDatas_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, msgDatas_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.icewind.protobuf.db.DBOnlineMsgBlob.OnlineMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.icewind.protobuf.db.DBOnlineMsgBlob.OnlineMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.icewind.protobuf.db.DBOnlineMsgBlob.OnlineMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.icewind.protobuf.db.DBOnlineMsgBlob.OnlineMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.icewind.protobuf.db.DBOnlineMsgBlob.OnlineMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.icewind.protobuf.db.DBOnlineMsgBlob.OnlineMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.icewind.protobuf.db.DBOnlineMsgBlob.OnlineMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.icewind.protobuf.db.DBOnlineMsgBlob.OnlineMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.icewind.protobuf.db.DBOnlineMsgBlob.OnlineMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.icewind.protobuf.db.DBOnlineMsgBlob.OnlineMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.icewind.protobuf.db.DBOnlineMsgBlob.OnlineMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.icewind.protobuf.OnlineMsg}
     *
     * <pre>
     **
     * 玩家未处理的在线消息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.icewind.protobuf.OnlineMsg)
        com.icewind.protobuf.db.DBOnlineMsgBlob.OnlineMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.icewind.protobuf.db.DBOnlineMsgBlob.internal_static_com_icewind_protobuf_OnlineMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.icewind.protobuf.db.DBOnlineMsgBlob.internal_static_com_icewind_protobuf_OnlineMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.icewind.protobuf.db.DBOnlineMsgBlob.OnlineMsg.class, com.icewind.protobuf.db.DBOnlineMsgBlob.OnlineMsg.Builder.class);
      }

      // Construct using com.icewind.protobuf.db.DBOnlineMsgBlob.OnlineMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMsgDatasFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (msgDatasBuilder_ == null) {
          msgDatas_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          msgDatasBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.icewind.protobuf.db.DBOnlineMsgBlob.internal_static_com_icewind_protobuf_OnlineMsg_descriptor;
      }

      public com.icewind.protobuf.db.DBOnlineMsgBlob.OnlineMsg getDefaultInstanceForType() {
        return com.icewind.protobuf.db.DBOnlineMsgBlob.OnlineMsg.getDefaultInstance();
      }

      public com.icewind.protobuf.db.DBOnlineMsgBlob.OnlineMsg build() {
        com.icewind.protobuf.db.DBOnlineMsgBlob.OnlineMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.icewind.protobuf.db.DBOnlineMsgBlob.OnlineMsg buildPartial() {
        com.icewind.protobuf.db.DBOnlineMsgBlob.OnlineMsg result = new com.icewind.protobuf.db.DBOnlineMsgBlob.OnlineMsg(this);
        int from_bitField0_ = bitField0_;
        if (msgDatasBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            msgDatas_ = java.util.Collections.unmodifiableList(msgDatas_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.msgDatas_ = msgDatas_;
        } else {
          result.msgDatas_ = msgDatasBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.icewind.protobuf.db.DBOnlineMsgBlob.OnlineMsg) {
          return mergeFrom((com.icewind.protobuf.db.DBOnlineMsgBlob.OnlineMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.icewind.protobuf.db.DBOnlineMsgBlob.OnlineMsg other) {
        if (other == com.icewind.protobuf.db.DBOnlineMsgBlob.OnlineMsg.getDefaultInstance()) return this;
        if (msgDatasBuilder_ == null) {
          if (!other.msgDatas_.isEmpty()) {
            if (msgDatas_.isEmpty()) {
              msgDatas_ = other.msgDatas_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMsgDatasIsMutable();
              msgDatas_.addAll(other.msgDatas_);
            }
            onChanged();
          }
        } else {
          if (!other.msgDatas_.isEmpty()) {
            if (msgDatasBuilder_.isEmpty()) {
              msgDatasBuilder_.dispose();
              msgDatasBuilder_ = null;
              msgDatas_ = other.msgDatas_;
              bitField0_ = (bitField0_ & ~0x00000001);
              msgDatasBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMsgDatasFieldBuilder() : null;
            } else {
              msgDatasBuilder_.addAllMessages(other.msgDatas_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getMsgDatasCount(); i++) {
          if (!getMsgDatas(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.icewind.protobuf.db.DBOnlineMsgBlob.OnlineMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.icewind.protobuf.db.DBOnlineMsgBlob.OnlineMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData> msgDatas_ =
        java.util.Collections.emptyList();
      private void ensureMsgDatasIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          msgDatas_ = new java.util.ArrayList<com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData>(msgDatas_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData, com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData.Builder, com.icewind.protobuf.db.DBOnlineMsgBlob.MsgDataOrBuilder> msgDatasBuilder_;

      /**
       * <code>repeated .com.icewind.protobuf.MsgData msgDatas = 1;</code>
       */
      public java.util.List<com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData> getMsgDatasList() {
        if (msgDatasBuilder_ == null) {
          return java.util.Collections.unmodifiableList(msgDatas_);
        } else {
          return msgDatasBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.icewind.protobuf.MsgData msgDatas = 1;</code>
       */
      public int getMsgDatasCount() {
        if (msgDatasBuilder_ == null) {
          return msgDatas_.size();
        } else {
          return msgDatasBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.icewind.protobuf.MsgData msgDatas = 1;</code>
       */
      public com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData getMsgDatas(int index) {
        if (msgDatasBuilder_ == null) {
          return msgDatas_.get(index);
        } else {
          return msgDatasBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.icewind.protobuf.MsgData msgDatas = 1;</code>
       */
      public Builder setMsgDatas(
          int index, com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData value) {
        if (msgDatasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMsgDatasIsMutable();
          msgDatas_.set(index, value);
          onChanged();
        } else {
          msgDatasBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.icewind.protobuf.MsgData msgDatas = 1;</code>
       */
      public Builder setMsgDatas(
          int index, com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData.Builder builderForValue) {
        if (msgDatasBuilder_ == null) {
          ensureMsgDatasIsMutable();
          msgDatas_.set(index, builderForValue.build());
          onChanged();
        } else {
          msgDatasBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.icewind.protobuf.MsgData msgDatas = 1;</code>
       */
      public Builder addMsgDatas(com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData value) {
        if (msgDatasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMsgDatasIsMutable();
          msgDatas_.add(value);
          onChanged();
        } else {
          msgDatasBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.icewind.protobuf.MsgData msgDatas = 1;</code>
       */
      public Builder addMsgDatas(
          int index, com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData value) {
        if (msgDatasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMsgDatasIsMutable();
          msgDatas_.add(index, value);
          onChanged();
        } else {
          msgDatasBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.icewind.protobuf.MsgData msgDatas = 1;</code>
       */
      public Builder addMsgDatas(
          com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData.Builder builderForValue) {
        if (msgDatasBuilder_ == null) {
          ensureMsgDatasIsMutable();
          msgDatas_.add(builderForValue.build());
          onChanged();
        } else {
          msgDatasBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.icewind.protobuf.MsgData msgDatas = 1;</code>
       */
      public Builder addMsgDatas(
          int index, com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData.Builder builderForValue) {
        if (msgDatasBuilder_ == null) {
          ensureMsgDatasIsMutable();
          msgDatas_.add(index, builderForValue.build());
          onChanged();
        } else {
          msgDatasBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.icewind.protobuf.MsgData msgDatas = 1;</code>
       */
      public Builder addAllMsgDatas(
          java.lang.Iterable<? extends com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData> values) {
        if (msgDatasBuilder_ == null) {
          ensureMsgDatasIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, msgDatas_);
          onChanged();
        } else {
          msgDatasBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.icewind.protobuf.MsgData msgDatas = 1;</code>
       */
      public Builder clearMsgDatas() {
        if (msgDatasBuilder_ == null) {
          msgDatas_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          msgDatasBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.icewind.protobuf.MsgData msgDatas = 1;</code>
       */
      public Builder removeMsgDatas(int index) {
        if (msgDatasBuilder_ == null) {
          ensureMsgDatasIsMutable();
          msgDatas_.remove(index);
          onChanged();
        } else {
          msgDatasBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.icewind.protobuf.MsgData msgDatas = 1;</code>
       */
      public com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData.Builder getMsgDatasBuilder(
          int index) {
        return getMsgDatasFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.icewind.protobuf.MsgData msgDatas = 1;</code>
       */
      public com.icewind.protobuf.db.DBOnlineMsgBlob.MsgDataOrBuilder getMsgDatasOrBuilder(
          int index) {
        if (msgDatasBuilder_ == null) {
          return msgDatas_.get(index);  } else {
          return msgDatasBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.icewind.protobuf.MsgData msgDatas = 1;</code>
       */
      public java.util.List<? extends com.icewind.protobuf.db.DBOnlineMsgBlob.MsgDataOrBuilder> 
           getMsgDatasOrBuilderList() {
        if (msgDatasBuilder_ != null) {
          return msgDatasBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(msgDatas_);
        }
      }
      /**
       * <code>repeated .com.icewind.protobuf.MsgData msgDatas = 1;</code>
       */
      public com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData.Builder addMsgDatasBuilder() {
        return getMsgDatasFieldBuilder().addBuilder(
            com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData.getDefaultInstance());
      }
      /**
       * <code>repeated .com.icewind.protobuf.MsgData msgDatas = 1;</code>
       */
      public com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData.Builder addMsgDatasBuilder(
          int index) {
        return getMsgDatasFieldBuilder().addBuilder(
            index, com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData.getDefaultInstance());
      }
      /**
       * <code>repeated .com.icewind.protobuf.MsgData msgDatas = 1;</code>
       */
      public java.util.List<com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData.Builder> 
           getMsgDatasBuilderList() {
        return getMsgDatasFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData, com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData.Builder, com.icewind.protobuf.db.DBOnlineMsgBlob.MsgDataOrBuilder> 
          getMsgDatasFieldBuilder() {
        if (msgDatasBuilder_ == null) {
          msgDatasBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData, com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData.Builder, com.icewind.protobuf.db.DBOnlineMsgBlob.MsgDataOrBuilder>(
                  msgDatas_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          msgDatas_ = null;
        }
        return msgDatasBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.icewind.protobuf.OnlineMsg)
    }

    static {
      defaultInstance = new OnlineMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.icewind.protobuf.OnlineMsg)
  }

  public interface MsgDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.icewind.protobuf.MsgData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 type = 1;</code>
     *
     * <pre>
     **消息类型 
     * </pre>
     */
    boolean hasType();
    /**
     * <code>required int32 type = 1;</code>
     *
     * <pre>
     **消息类型 
     * </pre>
     */
    int getType();

    /**
     * <code>required bytes data = 2;</code>
     *
     * <pre>
     **消息体 
     * </pre>
     */
    boolean hasData();
    /**
     * <code>required bytes data = 2;</code>
     *
     * <pre>
     **消息体 
     * </pre>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code com.icewind.protobuf.MsgData}
   *
   * <pre>
   **
   * 单个消息
   * </pre>
   */
  public static final class MsgData extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.icewind.protobuf.MsgData)
      MsgDataOrBuilder {
    // Use MsgData.newBuilder() to construct.
    private MsgData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MsgData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MsgData defaultInstance;
    public static MsgData getDefaultInstance() {
      return defaultInstance;
    }

    public MsgData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MsgData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              type_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.icewind.protobuf.db.DBOnlineMsgBlob.internal_static_com_icewind_protobuf_MsgData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.icewind.protobuf.db.DBOnlineMsgBlob.internal_static_com_icewind_protobuf_MsgData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData.class, com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData.Builder.class);
    }

    public static com.google.protobuf.Parser<MsgData> PARSER =
        new com.google.protobuf.AbstractParser<MsgData>() {
      public MsgData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MsgData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MsgData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>required int32 type = 1;</code>
     *
     * <pre>
     **消息类型 
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 type = 1;</code>
     *
     * <pre>
     **消息类型 
     * </pre>
     */
    public int getType() {
      return type_;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>required bytes data = 2;</code>
     *
     * <pre>
     **消息体 
     * </pre>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes data = 2;</code>
     *
     * <pre>
     **消息体 
     * </pre>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private void initFields() {
      type_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, data_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.icewind.protobuf.MsgData}
     *
     * <pre>
     **
     * 单个消息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.icewind.protobuf.MsgData)
        com.icewind.protobuf.db.DBOnlineMsgBlob.MsgDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.icewind.protobuf.db.DBOnlineMsgBlob.internal_static_com_icewind_protobuf_MsgData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.icewind.protobuf.db.DBOnlineMsgBlob.internal_static_com_icewind_protobuf_MsgData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData.class, com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData.Builder.class);
      }

      // Construct using com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.icewind.protobuf.db.DBOnlineMsgBlob.internal_static_com_icewind_protobuf_MsgData_descriptor;
      }

      public com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData getDefaultInstanceForType() {
        return com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData.getDefaultInstance();
      }

      public com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData build() {
        com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData buildPartial() {
        com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData result = new com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData) {
          return mergeFrom((com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData other) {
        if (other == com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasData()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.icewind.protobuf.db.DBOnlineMsgBlob.MsgData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ ;
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       **消息类型 
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       **消息类型 
       * </pre>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       **消息类型 
       * </pre>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       **消息类型 
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes data = 2;</code>
       *
       * <pre>
       **消息体 
       * </pre>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes data = 2;</code>
       *
       * <pre>
       **消息体 
       * </pre>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>required bytes data = 2;</code>
       *
       * <pre>
       **消息体 
       * </pre>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes data = 2;</code>
       *
       * <pre>
       **消息体 
       * </pre>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.icewind.protobuf.MsgData)
    }

    static {
      defaultInstance = new MsgData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.icewind.protobuf.MsgData)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_icewind_protobuf_OnlineMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_icewind_protobuf_OnlineMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_icewind_protobuf_MsgData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_icewind_protobuf_MsgData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024db/DBOnlineMsg.proto\022\024com.icewind.prot" +
      "obuf\"<\n\tOnlineMsg\022/\n\010msgDatas\030\001 \003(\0132\035.co" +
      "m.icewind.protobuf.MsgData\"%\n\007MsgData\022\014\n" +
      "\004type\030\001 \002(\005\022\014\n\004data\030\002 \002(\014B*\n\027com.icewind" +
      ".protobuf.dbB\017DBOnlineMsgBlob"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_icewind_protobuf_OnlineMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_icewind_protobuf_OnlineMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_icewind_protobuf_OnlineMsg_descriptor,
        new java.lang.String[] { "MsgDatas", });
    internal_static_com_icewind_protobuf_MsgData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_icewind_protobuf_MsgData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_icewind_protobuf_MsgData_descriptor,
        new java.lang.String[] { "Type", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
