#define ASPNET_STATE_OBJECT                                0
#define ASPNET_STATE_SERVICE_SESSIONS_ACTIVE               206
#define ASPNET_STATE_SERVICE_SESSIONS_ABANDONED            208
#define ASPNET_STATE_SERVICE_SESSIONS_TIMED_OUT            210
#define ASPNET_STATE_SERVICE_SESSIONS_TOTAL                212
