
			
// Generated by the SocketProtoGenerationTool.  DO NOT EDIT!
package com.mokylin.td.clientmsg.enumeration;

//
public enum EnumMenPai
{

			
		// 无职业
		NONE(0),

		
			
		// 真武
		ZHEN_WU(1),

		
			
		// 丐帮
		GAI_BANG(2),

		
			
		// 神威
		SHEN_WEI(3),

		
			
		// 太白
		TAI_BAI(4),

		
			
		// 唐门
		TANG_MEN(5),

		
			
		// 天香
		TIAN_XIANG(6),

		
			
		// 五毒
		WU_DU(7),

		
			
		// 神刀
		SHEN_DAO(8)

;

	private final int value;
	
	EnumMenPai(int value){
		this.value= value;
	}
	
	public int getValue() {
		return value;
	}

	public static EnumMenPai valueOf(int _value) {
		for (EnumMenPai each : EnumMenPai.values()) {
			if (each.value == _value) {
				return each;
			}
		}
		return null;
	}
}

		