
			
// Generated by the SocketProtoGenerationTool.  DO NOT EDIT!
package com.mokylin.td.clientmsg.enumeration;

//
public enum EnumBody
{

			
		// 成年男
		MALE_ADULT(0),

		
			
		// 成年女
		FEMALE_ADULT(1)

;

	private final int value;
	
	EnumBody(int value){
		this.value= value;
	}
	
	public int getValue() {
		return value;
	}

	public static EnumBody valueOf(int _value) {
		for (EnumBody each : EnumBody.values()) {
			if (each.value == _value) {
				return each;
			}
		}
		return null;
	}
}

		