// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MockMessageType.proto

package com.mokylin.bleach.test.protobuf;

public final class MockMessageType {
  private MockMessageType() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.mokylin.bleach.test.protobuf.MockMessageType.cgMessageType);
    registry.add(com.mokylin.bleach.test.protobuf.MockMessageType.gcMessageType);
  }
  /**
   * Protobuf enum {@code com.mokylin.test.CGMessageType}
   */
  public enum CGMessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CG_TEST = 501;</code>
     */
    CG_TEST(0, 501),
    /**
     * <code>CG_FUCK_OFF = 601;</code>
     */
    CG_FUCK_OFF(1, 601),
    /**
     * <code>CG_MAKE_LOVE = 777;</code>
     */
    CG_MAKE_LOVE(2, 777),
    /**
     * <code>CG_LOGIN = 888;</code>
     */
    CG_LOGIN(3, 888),
    ;

    /**
     * <code>CG_TEST = 501;</code>
     */
    public static final int CG_TEST_VALUE = 501;
    /**
     * <code>CG_FUCK_OFF = 601;</code>
     */
    public static final int CG_FUCK_OFF_VALUE = 601;
    /**
     * <code>CG_MAKE_LOVE = 777;</code>
     */
    public static final int CG_MAKE_LOVE_VALUE = 777;
    /**
     * <code>CG_LOGIN = 888;</code>
     */
    public static final int CG_LOGIN_VALUE = 888;


    public final int getNumber() { return value; }

    public static CGMessageType valueOf(int value) {
      switch (value) {
        case 501: return CG_TEST;
        case 601: return CG_FUCK_OFF;
        case 777: return CG_MAKE_LOVE;
        case 888: return CG_LOGIN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CGMessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<CGMessageType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CGMessageType>() {
            public CGMessageType findValueByNumber(int number) {
              return CGMessageType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.mokylin.bleach.test.protobuf.MockMessageType.getDescriptor().getEnumTypes().get(0);
    }

    private static final CGMessageType[] VALUES = values();

    public static CGMessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private CGMessageType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.mokylin.test.CGMessageType)
  }

  /**
   * Protobuf enum {@code com.mokylin.test.GCMessageType}
   */
  public enum GCMessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>GC_TEST = 500;</code>
     */
    GC_TEST(0, 500),
    /**
     * <code>GC_LOGIN = 501;</code>
     */
    GC_LOGIN(1, 501),
    ;

    /**
     * <code>GC_TEST = 500;</code>
     */
    public static final int GC_TEST_VALUE = 500;
    /**
     * <code>GC_LOGIN = 501;</code>
     */
    public static final int GC_LOGIN_VALUE = 501;


    public final int getNumber() { return value; }

    public static GCMessageType valueOf(int value) {
      switch (value) {
        case 500: return GC_TEST;
        case 501: return GC_LOGIN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<GCMessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<GCMessageType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<GCMessageType>() {
            public GCMessageType findValueByNumber(int number) {
              return GCMessageType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.mokylin.bleach.test.protobuf.MockMessageType.getDescriptor().getEnumTypes().get(1);
    }

    private static final GCMessageType[] VALUES = values();

    public static GCMessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private GCMessageType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.mokylin.test.GCMessageType)
  }

  public static final int CG_MESSAGE_TYPE_FIELD_NUMBER = 50001;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      com.mokylin.bleach.test.protobuf.MockMessageType.CGMessageType> cgMessageType = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.mokylin.bleach.test.protobuf.MockMessageType.CGMessageType.class,
        null);
  public static final int GC_MESSAGE_TYPE_FIELD_NUMBER = 50002;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      com.mokylin.bleach.test.protobuf.MockMessageType.GCMessageType> gcMessageType = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.mokylin.bleach.test.protobuf.MockMessageType.GCMessageType.class,
        null);

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025MockMessageType.proto\022\020com.mokylin.tes" +
      "t\032 google/protobuf/descriptor.proto*Q\n\rC" +
      "GMessageType\022\014\n\007CG_TEST\020\365\003\022\020\n\013CG_FUCK_OF" +
      "F\020\331\004\022\021\n\014CG_MAKE_LOVE\020\211\006\022\r\n\010CG_LOGIN\020\370\006*," +
      "\n\rGCMessageType\022\014\n\007GC_TEST\020\364\003\022\r\n\010GC_LOGI" +
      "N\020\365\003:[\n\017cg_message_type\022\037.google.protobu" +
      "f.MessageOptions\030\321\206\003 \001(\0162\037.com.mokylin.t" +
      "est.CGMessageType:[\n\017gc_message_type\022\037.g" +
      "oogle.protobuf.MessageOptions\030\322\206\003 \001(\0162\037." +
      "com.mokylin.test.GCMessageTypeB3\n com.mo",
      "kylin.bleach.test.protobufB\017MockMessageT" +
      "ype"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          cgMessageType.internalInit(descriptor.getExtensions().get(0));
          gcMessageType.internalInit(descriptor.getExtensions().get(1));
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
